name: Python Test
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
        
      - name: install python
        run:  |
          python -m pip install --upgrade pip
          pip install flake8 nose
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


      - name: linter
        run: |
          flake8 .

      - name: nosetest
        run: |
          nosetest
          
      
    
